# These categories will be applied to all DAGs in the repo.
categories:
  - Airflow Fundamentals
  - Alerts/Notifications
# List of DAGs that should be published to the Astronomer Registry.
dags:
  - path: dags/slack_callback_dag.py
  - path: dags/slack_callback_partial_dag.py
